version: '2.1'

services:
  cassandra:
    image: cassandra:3.0
    ports:
      - 9042:9042
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5

  kairosdb: 
    build: .
    environment: 
      - CASSANDRA_HOSTS=cassandra
    ports: 
      - "8080:8080" 
    depends_on:
      cassandra:
        condition: service_healthy


  