version: '2.1'

services:
  cassandra:
    image: cassandra:3.0
    environment: 
      #enable thrift connections
      - CASSANDRA_START_RPC=true 
    ports:
      - 9042:9042
      - 9160:9160
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5

  kairosdb: 
    build: .
    ports: 
      - "8080:8080" 
    depends_on:
      cassandra:
        condition: service_healthy
    entrypoint: /opt/kairosdb/bin/kairosdb.sh run 


  